# -*- coding: utf-8 -*-
"""
配置模块入口
"""
from .settings import *
from .douyin_config import *

__all__ = [
    'PLATFORM', 'LOGIN_TYPE', 'COOKIES', 'CRAWLER_TYPE',
    'HEADLESS', 'SAVE_LOGIN_STATE', 'USER_DATA_DIR',
    'ENABLE_CDP_MODE', 'CDP_DEBUG_PORT', 'CUSTOM_BROWSER_PATH',
    'CDP_HEADLESS', 'BROWSER_LAUNCH_TIMEOUT', 'AUTO_CLOSE_BROWSER',
    'START_PAGE', 'CRAWLER_MAX_NOTES_COUNT', 'MAX_CONCURRENCY_NUM',
    'CRAWLER_MAX_SLEEP_SEC', 'ENABLE_GET_MEDIA', 'ENABLE_IP_PROXY',
    'IP_PROXY_POOL_COUNT', 'IP_PROXY_PROVIDER_NAME',
    'DATABASE_PATH', 'VIDEO_SAVE_DIR', 'IMAGE_SAVE_DIR',
    'KEYWORDS', 'PUBLISH_TIME_TYPE', 'DY_SPECIFIED_ID_LIST', 'DY_CREATOR_ID_LIST'
]
